PORT_NUM = 4

moduleName = "ArbiterComb_x" + str(PORT_NUM)
f = open(moduleName + ".v", "w+")

f.write("//" + '-'*75 + '\n')
f.write("// This arbiter can be used to replace the arbiter in the multi-layer\n")
f.write("// AHB Bus Matrix offered by ARM System Design Kit. This arbiter appears\n")
f.write("// with the same interface/portlist aiming to easy replacement/integration.\n")
f.write("// However, an arbitration strategy of combinatorial logic is implemented\n")
f.write("// with the advantage of saving one cycle. Namely the arbitration results\n")
f.write("// addr_in_port and no_port are available \"instantly\" within the same\n")
f.write("// cycle the requests comes, rather than a cycle delay in the ARM original\n")
f.write("// one. The downside is longer combinatorial path to balance, along with a\n")
f.write("// bit overheads.\n")
f.write("//\n")
f.write("// This file is generated by a Python script giving a parameter of the number\n")
f.write("// of input ports. The script is authored by Cheng Cai.\n")
f.write("//" + '-'*75 + '\n')

f.write('\n')
f.write("`timescale 1ns/1ps\n")
f.write('\n')

f.write("module " + moduleName + "(\n")
f.write('\n')
f.write(' '*4 + "input".ljust(8) + "wire".ljust(8) + ''.ljust(8) + "HCLK".ljust(12) + ",\n")
f.write(' '*4 + "input".ljust(8) + "wire".ljust(8) + ''.ljust(8) + "HRESETn".ljust(12) + ",\n")
f.write('\n')
for i in range(PORT_NUM):
    f.write(' '*4 + "input".ljust(8) + "wire".ljust(8) + ''.ljust(8) + ("req_port" + str(i)).ljust(12) + ",\n")
f.write('\n')
f.write(' '*4 + "input".ljust(8) + "wire".ljust(8) + ''.ljust(8) + "HREADYM".ljust(12) + ",\n")
f.write(' '*4 + "input".ljust(8) + "wire".ljust(8) + ''.ljust(8) + "HSELM".ljust(12) + ",\n")
f.write(' '*4 + "input".ljust(8) + "wire".ljust(8) + "[1:0]".ljust(8) + "HTRANSM".ljust(12) + ",\n")
f.write(' '*4 + "input".ljust(8) + "wire".ljust(8) + ''.ljust(8) + "HMASTLOCKM".ljust(12) + ",\n")
f.write('\n')
addrInPortWidth = (PORT_NUM-1).bit_length()
f.write(' '*4 + "output".ljust(8) + "reg".ljust(8) + ("[" + str(addrInPortWidth-1) + ":0]").ljust(8) + "addr_in_port".ljust(12) + ",\n")
f.write(' '*4 + "output".ljust(8) + "wire".ljust(8) + ''.ljust(8) + "no_port".ljust(12) + "\n")
f.write('\n')
f.write(");\n\n")

f.write("reg".ljust(8) + ("[" + str(addrInPortWidth-1) + ":0]").ljust(8) + "last_addr_in_port".ljust(12) + ";\n")
f.write('\n'*2)

reqOrString = ""
pendOrString = ""
for i in range(PORT_NUM):
    reqOrString = reqOrString + "req_port" + str(i) + " | "
f.write("assign no_port = ~(" + reqOrString[:-3] + ") | ~HREADYM;\n")
f.write('\n')

f.write("always @(*) begin\n")
for i in range(PORT_NUM):
    ifElseIf = "if" if i==0 else "else if"
    f.write(' '*4 + ifElseIf + " (last_addr_in_port==" + str(addrInPortWidth) + "'d" + str(i) + ") begin\n")
    for j in range(PORT_NUM):
        ifElseIf = "if" if j==0 else "else if"
        nextNum = (i + j + 1)%PORT_NUM
        f.write(' '*8 + ifElseIf + " (req_port" + str(nextNum) + ") begin\n")
        f.write(' '*12 + "addr_in_port = " + str(addrInPortWidth) + "'d" + str(nextNum) + ";\n")
        f.write(' '*8 + "end\n")
    f.write(' '*8 + "else begin\n")
    f.write(' '*12 + "addr_in_port = " + str(addrInPortWidth) + "'d0;\n")
    f.write(' '*8 + "end\n")
    f.write(' '*4 + "end\n")
f.write(' '*4 + "else begin\n")
f.write(' '*8 + "addr_in_port = " + str(addrInPortWidth) + "'d0;\n")
f.write(' '*4 + "end\n")
f.write("end\n\n")

f.write("always @(negedge HRESETn or posedge HCLK) begin\n")
f.write(' '*4 + "if (~HRESETn) begin\n")
f.write(' '*8 + "last_addr_in_port <= " + str(addrInPortWidth) + "'d0;\n")
f.write(' '*4 + "end\n")
f.write(' '*4 + "else if (~no_port) begin\n")
f.write(' '*8 + "last_addr_in_port <= addr_in_port;\n")
f.write(' '*4 + "end\n")
f.write("end\n\n")

f.write("endmodule")
f.close()
